[package]

name = "rtforth"
version = "0.1.17"
authors = ["Sirius Wu <ccwu660601@mapacode.tw>"]

[dependencies]
getopts = "0.2"
time = "0.1"
rustyline = { git="https://github.com/chengchangwu/rustyline.git" }
byteorder = "0.4.2"

[profile.release]
debug = true
