[package]

name = "rtforth"
version = "0.5.0"
authors = ["Sirius Wu <ccwu660601@mapacode.tw>"]
keywords = ["forth", "real-time"]
description = "Forth implemented in Rust for realtime application"
license = "MIT OR Apache-2.0"
repository = "https://github.com/chengchangwu/rtforth.git"

[lib]
name = "rtforth"
path = "src/lib.rs"

[[bin]]
name = "rf"
path = "src/rf/rf.rs"

[dependencies]
time = "0.1"
uom = "0.18"
approx = "0.2"
libc = "0.2.41"
rustyline = "1.0"
getopts = "0.2"

[profile.release]
debug = true

[features]
default = []
subroutine-threaded = []
