[package]

name = "rtforth"
version = "0.1.36"
authors = ["Sirius Wu <ccwu660601@mapacode.tw>"]
keywords = ["forth", "real-time"]
description = "Forth implemented in Rust for realtime application"
license = "MIT OR Apache-2.0"
repository = "https://github.com/chengchangwu/rtforth.git"

[dependencies]
byteorder = "0.5"
time = "0.1"

[profile.release]
debug = true

[dev-dependencies]
getopts = "0.2"
rustyline = "1.0.0"
futures = "0.1.14"
tokio-core = "0.1.7"

[features]
default = []
primitive-centric = []
subroutine-threaded = []
