[package]

name = "rtforth"
version = "0.6.0"
authors = ["Sirius Wu <ccwu660601@mapacode.tw>"]
keywords = ["forth", "real-time"]
description = "Forth implemented in Rust for realtime application"
license = "MIT OR Apache-2.0"
repository = "https://github.com/chengchangwu/rtforth.git"
autoexamples = false

[lib]
name = "rtforth"
path = "src/lib.rs"

[[example]]
name = "rf"
path = "examples/rf.rs"

[[example]]
name = "multitask"
path = "examples/multitask.rs"

[[example]]
name = "simple"
path = "examples/simple.rs"

[dependencies]
uom = "=0.18.0"
approx = "=0.2.1"
libc = "=0.2.48"
hibitset = "=0.5.0"

[dev-dependencies]
rustyline = "1.0"
getopts = "=0.2.15"
time = "0.1"
lazy_static = "=1.3.0"

[profile.release]
debug = true

[features]
default = []
stc = []
