[package]

name = "rtforth"
version = "0.1.26"
authors = ["Sirius Wu <ccwu660601@mapacode.tw>"]
keywords = ["forth", "real-time"]
description = "Forth implemented in Rust for realtime application"
license = "MIT OR Apache-2.0"
repository = "https://github.com/chengchangwu/rtforth.git"

[dependencies]
getopts = "0.2"
time = "0.1"
rustyline = "1.0.0"
byteorder = "0.5"

[profile.release]
debug = true
